Repository carbon-design-system/carbon-for-ibm-dotcom-website, pull requests merged in 2020-10, with the labels that each got.

#679 chore(gatsby-theme-carbon): updating to version 1.26.11
  .yarn/offline-mirror/carbon-components-10.15.0.tgz
  .yarn/offline-mirror/carbon-components-react-7.15.0.tgz
  .yarn/offline-mirror/compute-scroll-into-view-1.0.14.tgz
  .yarn/offline-mirror/downshift-5.0.5.tgz
  .yarn/offline-mirror/gatsby-theme-carbon-1.26.2.tgz
  package.json
  yarn.lock
Labels: Ready to merge

#688 feat(rename): renaming to Carbon for IBM.com
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/question.md
  .github/SUPPORT.md
  README.md
  gatsby-config.js
  src/data/nav-items.yaml
  src/gatsby-theme-carbon/components/Header.js
  src/pages/components/gallery.mdx
  src/pages/components/leadspace.mdx
  src/pages/components/overview.mdx
  src/pages/contributions/index.mdx
  src/pages/events/summit-2020/agenda.mdx
  src/pages/events/summit-2020/introduction.mdx
  src/pages/events/summit-2020/resources.mdx
  src/pages/get-started/coding.mdx
  src/pages/get-started/designing.mdx
  src/pages/get-started/index.mdx
  src/pages/guidelines/expressive-theme.mdx
  src/pages/help/faqs.mdx
  src/pages/help/index.mdx
  src/pages/index.mdx
  src/pages/patterns/cards.mdx
  src/pages/patterns/index.mdx
  src/pages/resources/index.mdx
Labels: Ready to merge

#676 Update right-to-left.mdx
  src/pages/guidelines/right-to-left.mdx
Labels: Ready to merge

#692 fix(footer): properly set the path prefix of the contribution link
  src/gatsby-theme-carbon/components/Footer.js
Labels: Ready to merge, hacktoberfest-accepted

#691 Summit 2020 4
  src/pages/events/summit-2020/agenda.mdx
  src/pages/events/summit-2020/images/lead-space--desktop-4.jpg
  src/pages/events/summit-2020/images/team/akira-sudoh.png
  src/pages/events/summit-2020/images/team/andy-sherman.jpg
  src/pages/events/summit-2020/images/team/jacob-ottesen.jpg
  src/pages/events/summit-2020/images/team/jacob-ottesen.png
  src/pages/events/summit-2020/images/team/jen-price.jpg
  src/pages/events/summit-2020/images/team/jenny-sanchez.jpg
  src/pages/events/summit-2020/images/team/missy-foristall-old.jpg
  src/pages/events/summit-2020/images/team/nigel-prentice.jpg
  src/pages/events/summit-2020/images/team/olivia-flory.jpg
  src/pages/events/summit-2020/images/team/raph-amadeu.png
  src/pages/events/summit-2020/images/team/ryan-sebade.jpg
  src/pages/events/summit-2020/introduction.mdx
Labels: website: ibm.com library

#718 docs(slack): rename to #carbon-for-ibm-dotcom
  .github/ISSUE_TEMPLATE/question.md
  src/pages/404.js
  src/pages/contributions/components.mdx
  src/pages/get-started/index.mdx
  src/pages/guidelines/style-models/overview.mdx
  src/pages/guidelines/style-models/style-model-list.mdx
  src/pages/help/faqs.mdx
  src/pages/help/index.mdx
  src/pages/resources/index.mdx
Labels: Ready to merge
