Repository carbon-design-system/carbon-for-ibm-dotcom-website, pull requests merged in 2021-12, with the labels that each got.

#1372 Update resources link for content item horizontal
  src/data/components.json
Labels: Ready to merge

#1371 Update lead-space [Fix Broken Links].mdx
  src/pages/patterns/lead-space.mdx
Labels: design, content, Ready to merge, website

#1374 feat(step-3): add content for tutorial
  src/pages/developing/web-components-tutorial/step-3.mdx
Labels: Ready to merge

#1373 feat(tutorial): add step-2
  src/pages/developing/web-components-tutorial/step-2.mdx
Labels: Ready to merge

#1377 fix(step-3): link-list already should be imported
  src/pages/developing/web-components-tutorial/step-3.mdx
Labels: Ready to merge

#1379 feat(step-2): minor edits
  src/pages/developing/web-components-tutorial/step-1.mdx
  src/pages/developing/web-components-tutorial/step-2.mdx
  src/pages/developing/web-components-tutorial/step-3.mdx
Labels: Ready to merge

#1370 [Tabs extended] add modifier section
  src/images/component/tabs-extended-media/components--tabs-extended-media-1.jpg
  src/images/component/tabs-extended-media/components--tabs-extended-media-2.jpg
  src/images/component/tabs-extended/components--tabs-extended-1.png
  src/images/component/tabs-extended/components--tabs-extended-2.png
  src/images/component/tabs-extended/components--tabs-extended-3.png
  src/images/component/tabs-extended/components--tabs-extended-media-1.jpg
  src/images/component/tabs-extended/components--tabs-extended-media-1.png
  src/images/component/tabs-extended/components--tabs-extended-media-2.jpg
  src/images/component/tabs-extended/components--tabs-extended-media-2.png
  src/pages/components/tabs-extended.mdx
Labels: Ready to merge, website

#1378 Update leadspace [content guidance table].mdx
  src/pages/components/leadspace.mdx
Labels: design, content, Ready to merge, website

#1386 fix(tutorial): add github page link to preview
  src/pages/developing/web-components-tutorial/step-1.mdx
  src/pages/developing/web-components-tutorial/step-2.mdx
  src/pages/developing/web-components-tutorial/step-3.mdx
Labels: Ready to merge

#1387 fix(step-3): update to html comments
  src/pages/developing/web-components-tutorial/step-3.mdx
Labels: Ready to merge

#1388 docs(tutorial): update to dotcom shell setup steps
  src/pages/developing/web-components-tutorial/step-1.mdx
Labels: dev, Ready to merge

#1389 feat(tutorial): add step 5 content
  src/images/tutorial/deploy-on-github-pages.png
  src/pages/developing/web-components-tutorial/step-5.mdx
Labels: Ready to merge

#1390 make caption in image-w-caption optional
  src/pages/components/images.mdx
Labels: Ready to merge

#1393 fix(step-3): typos
  src/pages/developing/web-components-tutorial/step-3.mdx
Labels: Ready to merge

#1391 feat(tutorial): add step 4 content
  src/pages/developing/web-components-tutorial/step-4.mdx
Labels: Ready to merge

#1392 Website [Contributing] Component template updates
  src/pages/contributing/components.mdx
Labels: design, content, Ready to merge, website

#1396 fix(tutorial): add preview links to step 4 and 5
  src/pages/developing/web-components-tutorial/overview.mdx
  src/pages/developing/web-components-tutorial/step-4.mdx
  src/pages/developing/web-components-tutorial/step-5.mdx
Labels: Ready to merge

#1398 Website [Home page] Site description update
  src/gatsby-theme-carbon/templates/Homepage.js
Labels: design, content, Ready to merge, website

#1399 Website [Styling strategies] Remove duplication
  src/pages/guidelines/expressive-styling/styling-strategies.mdx
Labels: design, content, Ready to merge, website

#1395 Designing page update
  src/pages/designing/index.mdx
Labels: design, content, Ready to merge, website

#1402 removing guidelines overview page
  src/data/nav-items.yaml
  src/pages/guidelines/index.mdx
Labels: design, content, Ready to merge, website

#1381 feat(tutorial): update wrapping up step in the tutorial
  src/pages/developing/web-components-tutorial/wrapping-up.mdx
Labels: Ready to merge

#1403 chore(branch): replace references of `master` branch to `main`
  .github/ISSUE_TEMPLATE/bug_report.yaml
  .github/ISSUE_TEMPLATE/feature_request.yaml
  gatsby-node.js
  src/pages/contributing/components.mdx
  src/pages/contributing/overview.mdx
  src/pages/developing/frameworks/react.mdx
  src/pages/developing/index.mdx
  src/pages/developing/other-packages/index.mdx
  src/pages/resources/index.mdx
  wiki/UI-component/Footer.md
Labels: Ready to merge

#1404 docs(react-wrapper): update to use production url
  src/data/components.json
  src/pages/developing/frameworks/web-components.mdx
Labels: dev, Ready to merge

#1405 fix(components): update relative urls
  src/components/ComponentGallery/ComponentGallery.js
  src/components/ComponentList/ComponentList.js
  src/data/components.json
Labels: Ready to merge

#1400 Style models update
  src/data/nav-items.yaml
  src/images/guidelines/style-models/grid-above-max--dash.png
  src/images/guidelines/style-models/grid-above-max--doc.png
  src/images/guidelines/style-models/grid-above-max--editorial.png
  src/images/guidelines/style-models/grid-at-max.png
  src/images/guidelines/style-models/style-models-dashboard-do-dont-1.png
  src/images/guidelines/style-models/style-models-dashboard-do-dont-2.png
  src/images/guidelines/style-models/style-models-docu-1.png
  src/images/guidelines/style-models/style-models-docu-2.png
  src/images/guidelines/style-models/style-models-docu-3.png
  src/images/guidelines/style-models/style-models-docu-4.png
  src/images/guidelines/style-models/style-models-docu-example.png
  src/images/guidelines/style-models/style-models-docu-screen-regions.png
  src/images/guidelines/style-models/style-models-dotcom-shell-1.png
  src/images/guidelines/style-models/style-models-dotcom-shell-2.png
  src/images/guidelines/style-models/style-models-dotcom-shell-3.png
  src/images/guidelines/style-models/style-models-dotcom-shell-4.png
  src/images/guidelines/style-models/style-models-editorial-do-dont-1.png
  src/images/guidelines/style-models/style-models-editorial-do-dont-2.png
  src/images/guidelines/style-models/style-models-editorial-do-dont-3.png
  src/images/guidelines/style-models/style-models-editorial-example-layouts.png
  src/images/guidelines/style-models/style-models-editorial-screen-regions.png
  src/images/guidelines/style-models/style-models-highdens-example.png
  src/pages/guidelines/style-models.mdx
  src/pages/guidelines/style-models/images/color-themes.png
  src/pages/guidelines/style-models/images/dashboard-style-models.png
  src/pages/guidelines/style-models/images/editorial-nav-style-models.png
  src/pages/guidelines/style-models/images/grid-usage.png
  src/pages/guidelines/style-models/images/index-nav-style-models.png
  src/pages/guidelines/style-models/images/information-style-models.png
  src/pages/guidelines/style-models/images/journey-non-linear-dark.png
  src/pages/guidelines/style-models/images/journey-non-linear.png
  src/pages/guidelines/style-models/images/journey-progression-dark.png
  src/pages/guidelines/style-models/images/journey-progression.png
  src/pages/guidelines/style-models/images/learn-style-models.png
  src/pages/guidelines/style-models/images/listing-style-models.png
  src/pages/guidelines/style-models/images/screen-region-examples.png
  src/pages/guidelines/style-models/images/simple-transaction-style-models.png
  src/pages/guidelines/style-models/images/transaction-style-models.png
  src/pages/guidelines/style-models/images/type-scales-spacing.png
  src/pages/guidelines/style-models/overview.mdx
  src/pages/guidelines/style-models/style-model-list.mdx
Labels: design, content, Ready to merge, website

#1408 Website [Guidelines] Styling strategies page update
  src/pages/guidelines/expressive-styling/styling-strategies.mdx
Labels: design, content, Ready to merge, website

#1412 Contributing page topic order adjustment
  src/pages/contributing/components.mdx
Labels: design, content, Ready to merge, website

#1415 Content guidance table updates.mdx
  src/pages/components/back-to-top.mdx
  src/pages/components/callout-with-media.mdx
  src/pages/components/card-group.mdx
  src/pages/components/cards.mdx
  src/pages/components/content-block-media.mdx
  src/pages/components/images.mdx
  src/pages/components/link-with-icon.mdx
  src/pages/components/masthead.mdx
  src/pages/components/tag-link.mdx
  src/pages/components/video.mdx
Labels: design, content, Ready to merge, website
