Repository carbon-design-system/carbon-for-ibm-dotcom-website, pull requests merged in 2021-08, with the labels that each got.

#1118 chore: upgrading wiki workflow
  .github/workflows/repo-to-wiki.yml
Labels: Ready to merge

#1114 fix: component react wrapper storybook links
  src/data/components.json
Labels: Ready to merge

#1121 chore(gatsby): tweak create file logic
  gatsby-node.js
Labels: Ready to merge

#1099 Add images to components lacking them
  src/images/component/button-group/button-group.png
  src/images/component/carousel/carousel-overview.png
  src/images/component/content-block-horizontal/contentblockhorizontal-overview.png
  src/images/component/dotcom-shell/dotcomshell-overview.png
  src/images/component/pictogram-item/pictogramitem-overview.png
  src/images/component/quote/quote-overview.png
  src/pages/components/button-group.mdx
  src/pages/components/carousel.mdx
  src/pages/components/content-block-horizontal.mdx
  src/pages/components/dotcom-shell.mdx
  src/pages/components/pictogram-item.mdx
  src/pages/components/quote.mdx
Labels: Ready to merge

#1122 [image, image with caption] Migrating functional specs
  wiki/UI-component/Image-with-caption.md
  wiki/UI-component/Image.md
Labels: Ready to merge

#1119 [tabs-extended] Added annotated images
  wiki/Layout-component/Tabs-extended.md
  wiki/UI-component/CTA.md
Labels: Ready to merge

#1123 feat(resources): update to use mini cards
  src/components/ComponentFooter/ComponentFooter.js
  src/components/ComponentList/ComponentList.js
  src/components/ResourceLinks/ResourceLinks.js
  src/components/ResourceLinks/index.js
  src/components/SpecLinks/SpecLinks.js
  src/components/SpecLinks/index.js
  src/images/web-components-icon.svg
  src/pages/components/back-to-top.mdx
  src/pages/components/button-group.mdx
  src/pages/components/callout-quote.mdx
  src/pages/components/callout-with-media.mdx
  src/pages/components/card-group.mdx
  src/pages/components/card-in-card.mdx
  src/pages/components/card-link.mdx
  src/pages/components/card-section-carousel.mdx
  src/pages/components/card-section-images.mdx
  src/pages/components/card-section.mdx
  src/pages/components/card.mdx
  src/pages/components/carousel.mdx
  src/pages/components/content-block-cards.mdx
  src/pages/components/content-block-horizontal.mdx
  src/pages/components/content-block-media.mdx
  src/pages/components/content-block-segmented.mdx
  src/pages/components/content-block-simple.mdx
  src/pages/components/content-group-banner.mdx
  src/pages/components/content-group-cards.mdx
  src/pages/components/content-group-pictograms.mdx
  src/pages/components/content-group-simple.mdx
  src/pages/components/content-item-horizontal.mdx
  src/pages/components/cta-section.mdx
  src/pages/components/cta.mdx
  src/pages/components/dotcom-shell.mdx
  src/pages/components/expressive-modal.mdx
  src/pages/components/feature-card.mdx
  src/pages/components/feature-section.mdx
  src/pages/components/filter-panel.mdx
  src/pages/components/footer.mdx
  src/pages/components/horizontal-rule.mdx
  src/pages/components/image-with-caption.mdx
  src/pages/components/image.mdx
  src/pages/components/language-selector.mdx
  src/pages/components/layout.mdx
  src/pages/components/lead-space-block.mdx
  src/pages/components/lead-space-search.mdx
  src/pages/components/leadspace.mdx
  src/pages/components/leaving-ibm.mdx
  src/pages/components/lightbox-media-viewer.mdx
  src/pages/components/link-list-section.mdx
  src/pages/components/link-list.mdx
  src/pages/components/link-with-icon.mdx
  src/pages/components/localemodal.mdx
  src/pages/components/logo-grid.mdx
  src/pages/components/masthead.mdx
  src/pages/components/pictogram-item.mdx
  src/pages/components/quote.mdx
  src/pages/components/table-of-contents.mdx
  src/pages/components/tabs-extended-media.mdx
  src/pages/components/tabs-extended.mdx
  src/pages/components/tag-link.mdx
  src/pages/components/video.mdx
Labels: Ready to merge

#1129 docs: change Default to Overview for component page H2s
  src/pages/components/back-to-top.mdx
  src/pages/components/button-group.mdx
  src/pages/components/callout-quote.mdx
  src/pages/components/callout-with-media.mdx
  src/pages/components/card-group.mdx
  src/pages/components/card-in-card.mdx
  src/pages/components/card-link.mdx
  src/pages/components/card-section-carousel.mdx
  src/pages/components/card-section-images.mdx
  src/pages/components/card-section.mdx
  src/pages/components/card.mdx
  src/pages/components/content-block-cards.mdx
  src/pages/components/content-block-media.mdx
  src/pages/components/content-block-segmented.mdx
  src/pages/components/content-block-simple.mdx
  src/pages/components/content-group-banner.mdx
  src/pages/components/content-group-cards.mdx
  src/pages/components/content-group-pictograms.mdx
  src/pages/components/content-group-simple.mdx
  src/pages/components/content-item-horizontal.mdx
  src/pages/components/cta-section.mdx
Labels: Ready to merge

#1130 docs: change Default to Overview 2 of 2
  src/pages/components/expressive-modal.mdx
  src/pages/components/feature-card.mdx
  src/pages/components/feature-section.mdx
  src/pages/components/filter-panel.mdx
  src/pages/components/footer.mdx
  src/pages/components/horizontal-rule.mdx
  src/pages/components/language-selector.mdx
  src/pages/components/lead-space-block.mdx
  src/pages/components/leaving-ibm.mdx
  src/pages/components/lightbox-media-viewer.mdx
  src/pages/components/link-list-section.mdx
  src/pages/components/link-list.mdx
  src/pages/components/link-with-icon.mdx
  src/pages/components/localemodal.mdx
  src/pages/components/logo-grid.mdx
  src/pages/components/pictogram-item.mdx
  src/pages/components/table-of-contents.mdx
  src/pages/components/tag-link.mdx
  src/pages/components/video.mdx
Labels: Ready to merge

#1132 IA: update nav to About Carbon for IBM.com
  src/data/nav-items.yaml
  src/pages/about-carbon-for-ibm.com/get-started.mdx
  src/pages/about-carbon-for-ibm.com/what-is-carbon-for-ibm.com.mdx
Labels: Ready to merge

#1124 [Masthead] Add reason why masthead must stay white
  src/pages/components/masthead.mdx
Labels: Ready to merge

#1112 docs: remove image with caption and tabs extended media pages
  src/components/ResourceLinks/ResourceLinks.js
  src/data/components.json
  src/data/nav-items.yaml
  src/images/component/image/image-option-caption.gif
  src/images/component/image/image-options-border.jpg
  src/images/component/image/image-options-caption.gif
  src/images/component/image/image-overview-default.jpg
  src/images/component/tabs-extended/components--tabs-extended-media-1.jpg
  src/images/component/tabs-extended/components--tabs-extended-media-2.jpg
  src/pages/components/button-group.mdx
  src/pages/components/image-with-caption.mdx
  src/pages/components/image.mdx
  src/pages/components/tabs-extended-media.mdx
  src/pages/components/tabs-extended.mdx
  src/pages/guidelines/index.mdx
Labels: Ready to merge

#1128 [Lead space search] add notification for "coming soon"
  src/pages/components/lead-space-search.mdx
Labels: Ready to merge

#1140 About Carbon updates
  src/pages/about-carbon-for-ibm.com/what-we-provide.mdx
Labels: Ready to merge

#1141 fix(ResourceLinks): add optional multicomponent for different heading
  src/components/ResourceLinks/ResourceLinks.js
Labels: Ready to merge

#1145 Docs--Images-paredown-redux
  src/components/ResourceLinks/ResourceLinks.js
  src/data/components.json
  src/data/nav-items.yaml
  src/images/component/image/image-option-caption.gif
  src/images/component/image/image-options-caption.gif
  src/pages/components/button-group.mdx
  src/pages/components/card-section.mdx
  src/pages/components/images.mdx
  src/pages/components/lead-space-search.mdx
  src/pages/components/leadspace.mdx
  src/pages/components/tabs-extended.mdx
Labels: Ready to merge

#1143 feat(docs): added web components template info
  src/pages/developing/frameworks/web-components.mdx
  src/pages/resources/index.mdx
Labels: dev, Ready to merge

#1136 Docs: Card section paredown
  src/data/nav-items.yaml
  src/pages/components/card-section-images.mdx
  src/pages/components/card-section.mdx
Labels: Ready to merge

#1146 docs(web-components): adding web components template to resources
  src/pages/resources/index.mdx
Labels: dev, Ready to merge

#1161 Beacon tool: content fix straight to curly quotes
  src/pages/resources/beacon.mdx
Labels: Ready to merge

#1170 fix(dev-pages): fix to properly build the auto generated dev pages
  gatsby-node.js
  package.json
Labels: dev
