Repository carbon-design-system/carbon-for-ibm-dotcom-website, pull requests merged in 2021-09, with the labels that each got.

#1169 Update "release schedule" card to link to issue 5888
  src/pages/index.mdx
Labels: Ready to merge

#1174 docs(steps-to-adopt): updated NPM vs CDN documentation
  src/pages/about-carbon-for-ibm.com/steps-to-adopt.mdx
Labels: Ready to merge

#1173 [CTA] Video cards poster optional
  wiki/UI-component/CTA.md
Labels: Ready to merge

#1153 designing page prep for expressive sunset
  src/pages/designing/index.mdx
  src/pages/guidelines/expressive-styling/styling-strategies.mdx
Labels: Ready to merge

#1177 Update locale modal images and content
  src/images/component/locale-modal/default-locale-modal.jpg
  src/images/component/locale-modal/locale-modal-country.png
  src/images/component/locale-modal/locale-modal-default.png
  src/pages/components/localemodal.mdx
Labels: Ready to merge, website

#1182 docs fix for designing page
  src/gatsby-theme-carbon/components/LeftNav/ResourceLinks.js
  src/pages/designing/index.mdx
  src/pages/guidelines/expressive-styling/overview.mdx
  src/pages/resources/index.mdx
Labels: Ready to merge

#1183 Fix for Box links on Designing page
  src/pages/designing/index.mdx
Labels: Ready to merge

#1185 Update contributing link
  src/gatsby-theme-carbon/templates/Homepage.js
Labels: Ready to merge

#1186 chore(github): introduce CODEOWNERS file
  .github/CODEOWNERS
Labels: dev, Ready to merge

#1187 Web standards link added to Images component page
  src/pages/components/images.mdx
Labels: Ready to merge

#1188 Fix Home page broken link
  src/data/nav-items.yaml
  src/gatsby-theme-carbon/templates/Homepage.js
  src/pages/about-carbon-for-ibm.com/about.mdx
  src/pages/about-carbon-for-ibm.com/steps-to-adopt.mdx
  src/pages/about-carbon-for-ibm.com/what-we-provide.mdx
Labels: Ready to merge

#1192 Expressive styling coming soon update
  src/pages/guidelines/expressive-styling/overview.mdx
Labels: Ready to merge

#1195 chore(issue-templates): updating issue templates for the website
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/bug_report.yaml
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/feature_request.yaml
  .github/ISSUE_TEMPLATE/question.md
  .github/ISSUE_TEMPLATE/user_story.yaml
  .prettierignore
Labels: dev, Ready to merge

#1193 feat(tutorial): addiing initial web components tutorial
  .prettierrc.json
  .yarn/offline-mirror/caniuse-lite-1.0.30001102.tgz
  .yarn/offline-mirror/caniuse-lite-1.0.30001185.tgz
  .yarn/offline-mirror/caniuse-lite-1.0.30001258.tgz
  .yarn/offline-mirror/dotenv-10.0.0.tgz
  gatsby-config.js
  package.json
  src/components/Preview/Preview.module.scss
  src/components/Preview/index.js
  src/pages/developing/web-components-tutorial/overview.mdx
  src/pages/developing/web-components-tutorial/step-1.mdx
  src/pages/developing/web-components-tutorial/step-2.mdx
  src/pages/developing/web-components-tutorial/step-3.mdx
  src/pages/developing/web-components-tutorial/step-4.mdx
  src/pages/developing/web-components-tutorial/step-5.mdx
  src/pages/developing/web-components-tutorial/wrapping-up.mdx
  yarn.lock
Labels: Ready to merge

#1201 fix link to expressive styling
  src/pages/whats-happening/expressive-update.mdx
Labels: Ready to merge

#1207 website: Developing page, remove anchor links
  src/pages/developing/other-packages/index.mdx
Labels: Ready to merge

#1205 Website: expressive styling page updates
  src/images/guidelines/expressive-theme/compare-body2.png
  src/images/guidelines/expressive-theme/compare-components.png
  src/images/guidelines/expressive-theme/compare-headings.png
  src/images/guidelines/expressive-theme/compare-icon.png
  src/images/guidelines/expressive-theme/compare-typestyles.png
  src/images/guidelines/expressive-theme/container-size.png
  src/images/guidelines/expressive-theme/icon-size.png
  src/images/guidelines/expressive-theme/type-size.png
  src/pages/guidelines/expressive-styling/overview.mdx
  src/pages/guidelines/expressive-theme.mdx
  src/pages/help/expressive-update.mdx
Labels: Ready to merge
