Repository carbon-design-system/carbon-for-ibm-dotcom-website, pull requests merged in 2021-11, with the labels that each got.

#1297 Update leadspace [content guidance].mdx
  src/pages/components/leadspace.mdx
Labels: design, content, Ready to merge, website, hacktoberfest-accepted

#1336 Update content model table heading
  src/pages/components/back-to-top.mdx
  src/pages/components/callout-quote.mdx
  src/pages/components/card-group.mdx
  src/pages/components/card-section-carousel.mdx
  src/pages/components/card-section.mdx
  src/pages/components/cards.mdx
  src/pages/components/carousel.mdx
  src/pages/components/content-block-cards.mdx
  src/pages/components/content-block-horizontal.mdx
  src/pages/components/content-block-media.mdx
  src/pages/components/content-block-segmented.mdx
  src/pages/components/content-block-simple.mdx
  src/pages/components/content-block.mdx
  src/pages/components/content-group-banner.mdx
  src/pages/components/content-group-cards.mdx
  src/pages/components/content-group-pictograms.mdx
  src/pages/components/content-group-simple.mdx
  src/pages/components/content-group.mdx
  src/pages/components/content-item-horizontal.mdx
  src/pages/components/content-item.mdx
  src/pages/components/content-section.mdx
  src/pages/components/cta-section.mdx
  src/pages/components/feature-section.mdx
  src/pages/components/images.mdx
  src/pages/components/lead-space-block.mdx
  src/pages/components/lead-space-search.mdx
  src/pages/components/link-list-section.mdx
  src/pages/components/link-list.mdx
  src/pages/components/link-with-icon.mdx
  src/pages/components/logo-grid.mdx
  src/pages/components/pictogram-item.mdx
  src/pages/components/quote.mdx
  src/pages/components/table-of-contents.mdx
  src/pages/components/tabs-extended.mdx
  src/pages/components/tag-link.mdx
  src/pages/components/video.mdx
Labels: design, content, Ready to merge, website

#1325 Update lightbox-media-viewer [content guidance].mdx
  src/pages/components/lightbox-media-viewer.mdx
Labels: design, content, Ready to merge, website, hacktoberfest-accepted

#1335 Update masthead [content guidance].mdx
  src/pages/components/masthead.mdx
Labels: design, content, Ready to merge, website

#1331 [fs] Video service
  wiki/Feature-flag/Audio-player.md
  wiki/Service/Video-service.md
Labels: Ready to merge, Wiki, :eyes: eyes needed

#1334 Website [content]: Designing new content organization for kits
  src/data/nav-items.yaml
  src/pages/designing/figma-kit.mdx
  src/pages/designing/index.mdx
  src/pages/designing/sketch-kit.mdx
  src/pages/whats-happening/expressive-update.mdx
Labels: design, content, Ready to merge, website

#1353 Sketch kit page H2 update
  src/pages/designing/sketch-kit.mdx
Labels: design, content, Ready to merge, website

#1345 [fs] Universal banner
  wiki/Layout-component/Content-block.md
  wiki/Layout-component/universal-banner.md
  wiki/Publishing-guidelines/Functional-spec-template.md
Labels: Ready to merge, Wiki

#1355 [Docs] Card image update
  src/images/component/card/card-options-card-anatomy.png
  src/pages/components/cards.mdx
  src/pages/designing/figma-kit.mdx
Labels: Ready to merge, website

#1360 [Docs] Figma page
  src/images/get-started/Designing_Color_Styles_Figma.jpg
  src/images/get-started/Designing_Component_Variants_Figma.gif
  src/images/get-started/Designing_Components_Figma.gif
  src/images/get-started/Designing_Grid_Figma.gif
  src/images/get-started/Designing_Libraries_Figma.gif
  src/images/get-started/Designing_Text_Styles_Figma.jpg
  src/pages/components/cards.mdx
  src/pages/designing/figma-kit.mdx
Labels: Ready to merge, website

#1362 Cards page overview image update
  src/images/component/card/cards-preview-image-alt-6.png
  src/images/component/card/cards-preview.png
  src/pages/components/cards.mdx
Labels: Ready to merge

#1363 Figma page copyedits
  src/pages/designing/figma-kit.mdx
Labels: design, content, Ready to merge, website

#1366 fix(beacon): changed endpoint to live beacon API url
  src/components/BeaconWebUI/BeaconWebUI.js
Labels: dev
