Repository carbon-design-system/carbon-for-ibm-dotcom-website, pull requests merged in 2022-10, with the labels that each got.

#1528 chore(help): add office hours section
  src/pages/help/index.mdx
Labels: hacktoberfest-accepted

#1527 chore(help): updates to FAQ
  src/pages/help/faqs.mdx
Labels: Ready to merge, hacktoberfest-accepted

#1526 chore(help): tweaks to help content
  src/pages/help/index.mdx
Labels: Ready to merge, hacktoberfest-accepted

#1532 Updates to Other packages page
  src/pages/developing/other-packages/index.mdx
Labels: Ready to merge, hacktoberfest

#1533 Content section remove notification
  src/pages/components/content-section.mdx
Labels: Ready to merge, hacktoberfest-accepted

#1535 Resources fix broken links to storybook
  src/pages/resources/index.mdx
Labels: Ready to merge, hacktoberfest-accepted

#1529 Tweaks to spacing page
  src/pages/guidelines/spacing.mdx
Labels: Ready to merge, hacktoberfest, hacktoberfest-accepted

#1537 Resource card updates - Resources + Frameworks
  src/pages/developing/frameworks/react-wrapper.mdx
  src/pages/developing/frameworks/react.mdx
  src/pages/developing/frameworks/web-components.mdx
  src/pages/resources/index.mdx
Labels: Ready to merge, hacktoberfest-accepted

#1538 Typo fix: from “broswer” to “browser”
  src/pages/components/masthead.mdx
Labels: Ready to merge

#1525 chore(tutorial): remove web components tutorial badge info
  src/pages/developing/web-components-tutorial/overview.mdx
  src/pages/developing/web-components-tutorial/step-1.mdx
  src/pages/developing/web-components-tutorial/step-2.mdx
  src/pages/developing/web-components-tutorial/step-3.mdx
  src/pages/developing/web-components-tutorial/step-4.mdx
  src/pages/developing/web-components-tutorial/step-5.mdx
  src/pages/developing/web-components-tutorial/wrapping-up.mdx
Labels: Ready to merge, hacktoberfest-accepted

#1542 Add art direction component
  src/images/about/ecosystem-diagram-mobile.png
  src/pages/about-carbon-for-ibm.com/about.mdx
  src/pages/designing/index.mdx
Labels: Ready to merge, hacktoberfest, hacktoberfest-accepted

#1530 Content spacing tables moved to Spacing page
  src/pages/guidelines/expressive-styling/type-pairing.mdx
  src/pages/guidelines/spacing.mdx
Labels: Ready to merge, hacktoberfest-accepted

#1539 Carousel update - anatomy and related components
  src/images/component/carousel/carousel-anatomy.png
  src/pages/components/carousel.mdx
Labels: design, Ready to merge, website, hacktoberfest-accepted

#1541 Docs--Tag-link-update
  src/data/components.json
  src/data/nav-items.yaml
  src/images/component/tags/components--tag-link.jpg
  src/images/component/tags/tags-card-tag-example.png
  src/images/component/tags/tags-tag-link-interaction.gif
  src/pages/components/tag-link.mdx
  src/pages/components/tags.mdx
Labels: Ready to merge, hacktoberfest-accepted

#1543 Docs: Content item horizontal updates
  src/images/component/content-item-horizontal/cih-default-1.png
  src/images/component/content-item-horizontal/cih-default-2.png
  src/images/component/content-item-horizontal/cih-media-do-1.png
  src/images/component/content-item-horizontal/cih-media-do-2.png
  src/images/component/content-item-horizontal/cih-media-dont.png
  src/images/component/content-item-horizontal/cih-thumb-do.png
  src/images/component/content-item-horizontal/cih-thumb-dont.png
  src/images/component/content-item-horizontal/cih-tips-tricks-mix.png
  src/images/component/content-item-horizontal/cih-tips-tricks-single.png
  src/images/component/content-item-horizontal/content-item-horiz-anatomy.png
  src/images/component/content-item-horizontal/content-item-horiz-default.png
  src/images/component/content-item-horizontal/content-item-horiz-featured.png
  src/images/component/content-item-horizontal/content-item-horiz-media.png
  src/images/component/content-item-horizontal/content-item-horiz-thumbnail.png
  src/pages/components/content-item-horizontal.mdx
Labels: Ready to merge
