Repository carbon-design-system/carbon-for-ibm-dotcom-website, pull requests merged in 2022-01, with the labels that each got.

#1420 Update component links, status and order json
  src/components/ComponentGallery/images/cta.svg
  src/components/ComponentGallery/images/feature_section.svg
  src/components/ComponentGallery/images/language_selector.svg
  src/components/ComponentGallery/images/leaving_ibm_modal.svg
  src/components/ComponentGallery/images/link_list_section.svg
  src/components/ComponentGallery/images/link_with_icon.svg
  src/components/ComponentGallery/images/locale_modal.svg
  src/components/ComponentGallery/images/masthead.svg
  src/components/ComponentGallery/images/tabs_extended.svg
  src/components/ComponentGallery/images/tabs_extended_media.svg
  src/components/ComponentGallery/images/tag_link.svg
  src/data/components.json
Labels: design, Ready to merge, website

#1418 Update back-to-top [content guidance].mdx
  src/pages/components/back-to-top.mdx
Labels: design, content, Ready to merge, website

#1410 [Cards] Added Card logo
  src/images/component/card/card-modifier-logo-1.png
  src/images/component/card/card-modifier-logo-2.png
  src/images/component/card/card-modifier-logo-do-not.png
  src/images/component/card/card-modifier-logo-do.png
  src/pages/components/cards.mdx
Labels: Ready to merge, website

#1423 chore(codeowners): update to codeowners list
  .github/CODEOWNERS
Labels: dev, Ready to merge, housekeeping

#1417 content clean up: big sweep from audit
  src/pages/contributing/patterns.mdx
  src/pages/contributions/documentation.mdx
  src/pages/guidelines/content.mdx
  src/pages/resources/index.mdx
Labels: design, content, Ready to merge, website

#1414 universal banner component guidance
  src/components/ComponentGallery/images/universal_banner.svg
  src/data/components.json
  src/data/nav-items.yaml
  src/images/component/universal-banner/universal-banner--anatomy--928.png
  src/images/component/universal-banner/universal-banner--behaviors--448.png
  src/images/component/universal-banner/universal-banner--overview--928.png
  src/images/component/universal-banner/universal-banner--with-image--928.png
  src/images/component/universal-banner/universal-banner--with-text-only--928.png
  src/pages/components/universal-banner.mdx
Labels: design, Ready to merge

#1422 docs(tutorial): add badge image to wrapping up step
  src/images/developing/web-components-tutorial/developer_essentials_badge_carbon-for-ibm-dotcom.png
  src/pages/developing/web-components-tutorial/wrapping-up.mdx
Labels: Ready to merge

#1407 [Draft] Footnotes section func specs
  wiki/Carbon-component/Carbon-list.md
  wiki/Layout-component/Footnotes-section.md
Labels: Ready to merge, website, Wiki

#1439 docs(environments): remove all mybluemix.net urls
  src/data/components.json
  src/pages/developing/other-packages/index.mdx
  src/pages/developing/web-components-tutorial/step-4.mdx
  src/pages/resources/index.mdx
Labels: dev, Ready to merge

#1434 Docs footnote design only
  wiki/Design-only/Footnotes.md
  wiki/Layout-component/Footnotes-section.md
Labels: Ready to merge

#1438 Add filter panel storybook links
  src/data/components.json
  src/pages/components/filter-panel.mdx
Labels: Ready to merge

#1430 docs(tutorial): update badge image and final link to credly
  src/data/nav-items.yaml
  src/images/developing/web-components-tutorial/developer_essentials_badge_carbon-for-ibm-dotcom.png
  src/pages/developing/web-components-tutorial/wrapping-up.mdx
Labels: Ready to merge

#1442 fix(tutorial): fix step-3 and step-4 image paths
  src/pages/developing/web-components-tutorial/step-3.mdx
  src/pages/developing/web-components-tutorial/step-4.mdx
Labels: Ready to merge
