Repository carbon-design-system/carbon-for-ibm-dotcom-website, pull requests merged in 2022-07, with the labels that each got.

#1479 Update step-2.mdx
  src/pages/developing/web-components-tutorial/step-2.mdx
Labels: Ready to merge

#1489 Remove whats happening page 2
  src/data/nav-items.yaml
Labels: Ready to merge

#1494 Universal banner - Fixed resource card location
  src/pages/components/universal-banner.mdx
Labels: Ready to merge, website: standards, :eyes: eyes needed

#1496 Resources - added React wrapper card
  src/pages/resources/index.mdx
Labels: Ready to merge

#1498 ResourceCard reactwrapper - Back-to-top
  src/components/ResourceLinks/ResourceLinks.js
  src/data/components.json
  src/pages/components/back-to-top.mdx
Labels: Ready to merge, website

#1502 chore(react): add deprecation notice to react page
  src/pages/developing/frameworks/react.mdx
Labels: Ready to merge

#1490 fix: standardize card icon size
  src/styles/_homepage.scss
Labels: Ready to merge, website, :eyes: eyes needed

#1507 fix(nav): remove guidelines/overview link
  src/data/nav-items.yaml
Labels: Ready to merge

#1499 JSON Update + ResourceCard reorder
  src/components/ResourceLinks/ResourceLinks.js
  src/data/components.json
Labels: Ready to merge, website

#1508 chore(deps): various updates to `yarn.lock`
  .yarn/offline-mirror/@types-glob-7.1.4.tgz
  .yarn/offline-mirror/@types-glob-7.2.0.tgz
  .yarn/offline-mirror/@types-lodash-4.14.175.tgz
  .yarn/offline-mirror/@types-lodash-4.14.182.tgz
  .yarn/offline-mirror/@types-node-14.17.22.tgz
  .yarn/offline-mirror/@types-node-16.10.4.tgz
  .yarn/offline-mirror/@types-node-18.6.2.tgz
  .yarn/offline-mirror/devcert-1.2.0.tgz
  .yarn/offline-mirror/devcert-1.2.2.tgz
  .yarn/offline-mirror/get-intrinsic-1.1.2.tgz
  .yarn/offline-mirror/glob-7.2.3.tgz
  .yarn/offline-mirror/has-symbols-1.0.3.tgz
  .yarn/offline-mirror/is-ssh-1.3.3.tgz
  .yarn/offline-mirror/is-ssh-1.4.0.tgz
  .yarn/offline-mirror/is-valid-domain-0.1.6.tgz
  .yarn/offline-mirror/jpeg-js-0.4.3.tgz
  .yarn/offline-mirror/jpeg-js-0.4.4.tgz
  .yarn/offline-mirror/minimatch-3.1.2.tgz
  .yarn/offline-mirror/mkdirp-0.5.5.tgz
  .yarn/offline-mirror/mkdirp-0.5.6.tgz
  .yarn/offline-mirror/moment-2.29.3.tgz
  .yarn/offline-mirror/moment-2.29.4.tgz
  .yarn/offline-mirror/object-inspect-1.12.2.tgz
  .yarn/offline-mirror/parse-path-4.0.3.tgz
  .yarn/offline-mirror/parse-path-4.0.4.tgz
  .yarn/offline-mirror/parse-url-6.0.0.tgz
  .yarn/offline-mirror/parse-url-6.0.5.tgz
  .yarn/offline-mirror/protocols-2.0.1.tgz
  .yarn/offline-mirror/qs-6.10.1.tgz
  .yarn/offline-mirror/qs-6.11.0.tgz
  .yarn/offline-mirror/source-map-support-0.5.20.tgz
  .yarn/offline-mirror/source-map-support-0.5.21.tgz
  .yarn/offline-mirror/terser-4.8.0.tgz
  .yarn/offline-mirror/terser-4.8.1.tgz
  yarn.lock
Labels: Ready to merge
