Repository carbon-design-system/carbon-for-ibm-dotcom-website, pull requests merged in 2023-12, with the labels that each got.

#1729 Docs -- content block v2
  src/data/components.json
  src/data/nav-items.yaml
  src/images/component/content-block/component--content-block--overview.png
  src/images/component/content-block/content-block-anatomy.png
  src/images/component/content-block/content-block-behavior-01.png
  src/images/component/content-block/content-block-behavior-02.png
  src/images/component/content-block/content-block-gallery-01.png
  src/images/component/content-block/content-block-gallery-02.png
  src/images/component/content-block/content-block-gallery-03.png
  src/images/component/content-block/content-block-gallery-04.png
  src/images/component/content-block/content-block-modifiers-01.png
  src/images/component/content-block/content-block-modifiers-02.png
  src/images/component/content-block/content-block-modifiers-03.png
  src/images/component/content-block/content-block-overview.png
  src/images/component/content-block/content-block-usage-01.png
  src/images/component/content-block/content-block-usage-02.png
  src/images/component/content-section/content-section-anatomy.png
  src/images/component/content-section/content-section-behavior-01.png
  src/images/component/content-section/content-section-behavior-02.png
  src/images/component/content-section/content-section-modifier-children-01.png
  src/images/component/content-section/content-section-modifier-children-02.png
  src/images/component/content-section/content-section-modifier-heading-01.png
  src/images/component/content-section/content-section-modifier-heading-02.png
  src/images/component/content-section/content-section-modifier-heading-03.png
  src/images/component/content-section/content-section-modifier-heading-04.png
  src/images/component/content-section/content-section-modifier-heading-05.png
  src/images/component/content-section/content-section-overview.png
  src/pages/components/content-block.mdx
  src/pages/components/content-section.mdx
Labels: v2

#1730 feat(masthead): v2 updates
  src/data/components.json
  src/data/nav-items.yaml
  src/images/component/masthead/L0-anatomy.png
  src/images/component/masthead/L0-behavior-overflow.png
  src/images/component/masthead/L0-search-scoped.png
  src/images/component/masthead/L0-search.png
  src/images/component/masthead/L0-standard-menu.png
  src/images/component/masthead/L0-tabbed-menu.png
  src/images/component/masthead/L1-anatomy.png
  src/images/component/masthead/L1-menu-one-column.png
  src/images/component/masthead/L1-menu-pattern.png
  src/images/component/masthead/L1-menu-three-column.png
  src/images/component/masthead/L1-menu-two-column.png
  src/images/component/masthead/masthead-l0-anatomy.png
  src/images/component/masthead/masthead-l0-behavior-default.png
  src/images/component/masthead/masthead-l0-behavior-max-breakpoint.png
  src/images/component/masthead/masthead-l0-default.png
  src/images/component/masthead/masthead-l0-search-open-by-default.png
  src/images/component/masthead/masthead-l1-anatomy.png
  src/images/component/masthead/masthead-l1-behavior-default.png
  src/images/component/masthead/masthead-l1-behavior-dropdown.png
  src/images/component/masthead/masthead-l1-behavior-max-breakpoint.png
  src/images/component/masthead/masthead-l1-behavior-mobile.png
  src/images/component/masthead/masthead-l1-behavior-overflow-carousel.png
  src/images/component/masthead/masthead-l1.png
  src/images/component/masthead/masthead-megamenu_default.png
  src/images/component/masthead/masthead-megamenu_default_example2.png
  src/images/component/masthead/masthead-megamenu_variation_featuredlinks.png
  src/images/component/masthead/masthead-megamenu_variation_featuredlinks_primaryCTAhover.png
  src/images/component/masthead/masthead-megamenu_variation_linkswithdescription.png
  src/images/component/masthead/masthead-megamenu_variation_twotiers.png
  src/images/component/masthead/masthead-properties.png
  src/pages/components/dotcom-shell.mdx
  src/pages/components/lead-space-search.mdx
  src/pages/components/masthead.mdx
  src/pages/components/masthead/level-0-l0.mdx
  src/pages/components/masthead/level-1-l1.mdx
  src/pages/components/masthead/overview.mdx
  src/pages/components/table-of-contents.mdx
  src/pages/guidelines/expressive-styling/overview.mdx
  src/pages/guidelines/style-models.mdx
  src/pages/patterns/lead-space.mdx
Labels: v2

#1717 Docs--card group v2
  src/images/component/card-group/card-group-1.png
  src/images/component/card-group/card-group-2.png
  src/images/component/card-group/card-group-column.png
  src/images/component/card-group/card-group-modifiers-01.png
  src/images/component/card-group/card-group-modifiers-02.png
  src/images/component/card-group/card-group-modifiers-03.png
  src/images/component/card-group/card-group-modifiers-04.png
  src/images/component/card-group/card-group-modifiers-05.png
  src/images/component/card-group/card-group-offset.png
  src/images/component/card-group/card-group-overview.png
  src/images/component/card-group/card-group-variations-01.png
  src/pages/components/card-group.mdx
Labels: :eyes: eyes needed, v2

#1733 Docs--layout-guidelines-v2-updates
  src/images/guidelines/layout/layout_repitition_consistency_do.png
  src/images/guidelines/layout/layout_repitition_consistency_dont.png
  src/images/pattern/overview/patterns_overview_Repetition_section1_don't.png
  src/pages/guidelines/layout.mdx
Labels: :eyes: eyes needed, v2

#1722 chore(pages): hide various components/sections
  src/data/components.json
  src/data/nav-items.yaml
Labels: Ready to merge, website, v2

#1742 Docs--Updated Figma kit link
  src/pages/designing/design-kit.mdx
Labels: Ready to merge
