Repository carbon-design-system/carbon-for-ibm-dotcom-website, pull requests merged in 2023-09, with the labels that each got.

#1673 Link list updates v2
  src/images/component/link-list/link-list-end-of-section.png
  src/images/component/link-list/link-list-horizontal.png
  src/images/component/link-list/link-list-overview.png
  src/images/component/link-list/link-list-vertical.png
  src/pages/components/link-list.mdx
Labels: Ready to merge

#1670 Docs -- callout quote v2 & Resource Card update
  src/components/ResourceLinks/ResourceLinks.js
  src/images/component/callout-quote/cq-overview.png
  src/images/pattern/callout-quote/callout-quote.jpg
  src/pages/components/callout-quote.mdx
Labels: Ready to merge, v2

#1672 Docs--Callout-with-media-v2
  src/images/component/callout-with-media/cwm-overview.png
  src/images/pattern/callout-with-media/callout-with-media.jpg
  src/pages/components/callout-with-media.mdx
Labels: Ready to merge, v2

#1687 Feat/designing get started
  src/pages/designing/index.mdx
Labels: v2

#1685 chore(pages): remove & hide
  src/components/ComponentGallery/images/card_section.svg
  src/components/ComponentGallery/images/card_section_carousel.svg
  src/components/ComponentGallery/images/card_section_images.svg
  src/components/ComponentGallery/images/content_block_cards.svg
  src/components/ComponentGallery/images/content_block_horizontal.svg
  src/components/ComponentGallery/images/content_block_media.svg
  src/components/ComponentGallery/images/content_block_segmented.svg
  src/components/ComponentGallery/images/content_block_simple.svg
  src/components/ComponentGallery/images/content_group_cards.svg
  src/components/ComponentGallery/images/content_group_pictograms.svg
  src/components/ComponentGallery/images/content_group_simple.svg
  src/components/ComponentGallery/images/layout.svg
  src/components/ComponentGallery/images/link_list_section.svg
  src/components/ComponentGallery/images/pictogram_item.svg
  src/data/components.json
  src/data/nav-items.yaml
  src/pages/components/card-section-carousel.mdx
  src/pages/components/card-section.mdx
  src/pages/components/content-block-cards.mdx
  src/pages/components/content-block-horizontal.mdx
  src/pages/components/content-block-media.mdx
  src/pages/components/content-block-segmented.mdx
  src/pages/components/content-block-simple.mdx
  src/pages/components/content-block.mdx
  src/pages/components/content-group-cards.mdx
  src/pages/components/content-group-pictograms.mdx
  src/pages/components/content-group-simple.mdx
  src/pages/components/layout.mdx
  src/pages/components/link-list-section.mdx
  src/pages/components/pictogram-item.mdx
  src/pages/resources/index.mdx
  wiki/Layout-component/Content-block-cards.md
  wiki/Layout-component/Content-block-horizontal.md
  wiki/Layout-component/Content-block-media.md
  wiki/Layout-component/Content-block-mixed-groups.md
  wiki/Layout-component/Content-block-segmented.md
  wiki/Layout-component/Content-block-simple.md
  wiki/Layout-component/Content-block.md
Labels: Ready to merge, v2
