Repository carbon-design-system/carbon-for-ibm-dotcom-website, pull requests merged in 2023-10, with the labels that each got.

#1693 update feature section mdx
  src/images/component/feature-section/feature-section.png
  src/pages/components/feature-section.mdx
Labels: v2

#1695 Docs -- feature section v2 image
  src/images/component/feature-section/feature-section.png
Labels: hacktoberfest, v2

#1694 feat(content-item-row): update website v2
  src/components/ComponentGallery/images/content_item_row.svg
  src/data/components.json
  src/data/nav-items.yaml
  src/images/component/content-item-row/cir-default-1.png
  src/images/component/content-item-row/cir-default-2.png
  src/images/component/content-item-row/cir-media-do-1.png
  src/images/component/content-item-row/cir-media-do-2.png
  src/images/component/content-item-row/cir-media-dont.png
  src/images/component/content-item-row/cir-thumb-do.png
  src/images/component/content-item-row/cir-thumb-dont.png
  src/images/component/content-item-row/cir-tips-tricks-mix.png
  src/images/component/content-item-row/cir-tips-tricks-single.png
  src/images/component/content-item-row/content-item-row-anatomy.png
  src/images/component/content-item-row/content-item-row-default.png
  src/images/component/content-item-row/content-item-row-featured.png
  src/images/component/content-item-row/content-item-row-media.png
  src/images/component/content-item-row/content-item-row-thumbnail.png
  src/pages/components/content-item-row.mdx
  src/pages/components/content-item.mdx
  src/pages/components/tabs-extended.mdx
  wiki/Layout-component/Content-item-row.md
  wiki/Layout-component/Tabs-extended-media.md
Labels: hacktoberfest, v2

#1686 Docs -- designing design kit v2
  src/data/nav-items.yaml
  src/images/designing/design-kit/design-kit-I.png
  src/images/designing/design-kit/design-kit-II.png
  src/images/get-started/Designing_Color_Styles_Figma.jpg
  src/images/get-started/Designing_Component_Variants_Figma.gif
  src/images/get-started/Designing_Components_Figma.gif
  src/images/get-started/Designing_Grid_Figma.gif
  src/images/get-started/Designing_Grid_Sketch.jpg
  src/images/get-started/Designing_LayersStyles_Sketch.jpg
  src/images/get-started/Designing_Libraries_Figma.gif
  src/images/get-started/Designing_Symbols_Sketch.jpg
  src/images/get-started/Designing_TextStyles_Sketch.jpg
  src/images/get-started/Designing_Text_Styles_Figma.jpg
  src/pages/designing/design-kit.mdx
  src/pages/designing/figma-kit.mdx
  src/pages/designing/other-resources.mdx
  src/pages/designing/sketch-kit.mdx
  src/pages/index.mdx
  src/pages/whats-happening/expressive-update.mdx
Labels: hacktoberfest-accepted, v2

#1683 Docs -- Content item v2
  src/data/components.json
  src/images/component/content-item/component--content-item--behaviors-desktop.png
  src/images/component/content-item/component--content-item--behaviors-mobile.png
  src/images/component/content-item/component--content-item--overview.png
  src/images/component/content-item/content-item-media.png
  src/images/component/content-item/content-item-orientation-I.png
  src/images/component/content-item/content-item-orientation-II.png
  src/images/component/content-item/content-item-overview.png
  src/pages/components/content-item.mdx
  src/pages/components/feature-section.mdx
Labels: hacktoberfest, v2

#1697 chore(gitignore): add comment
  .gitignore
Labels: v2

#1704 Content item v2 – Add related content and anchor
  src/pages/components/content-item.mdx
Labels: hacktoberfest

#1698 Docs -- lead space v2
  src/data/components.json
  src/images/component/lead-space/component--lead-space--centered--4cols.jpg
  src/images/component/lead-space/component--lead-space--centered.jpg
  src/images/component/lead-space/component--lead-space--medium--4cols.jpg
  src/images/component/lead-space/component--lead-space--medium--tag-links.jpg
  src/images/component/lead-space/component--lead-space--medium.jpg
  src/images/component/lead-space/component--lead-space--short--4cols.jpg
  src/images/component/lead-space/component--lead-space--short.jpg
  src/images/component/lead-space/component--lead-space--super--4cols.jpg
  src/images/component/lead-space/component--lead-space--super--background-image.jpg
  src/images/component/lead-space/component--lead-space--super--background-video.jpg
  src/images/component/lead-space/component--lead-space--super--behaviors.jpg
  src/images/component/lead-space/component--lead-space--super--modifiers.jpg
  src/images/component/lead-space/component--lead-space--super--tag-links.jpg
  src/images/component/lead-space/component--lead-space--super.jpg
  src/images/component/lead-space/component--lead-space--tall--4cols.jpg
  src/images/component/lead-space/component--lead-space--tall--background-image.jpg
  src/images/component/lead-space/component--lead-space--tall.jpg
  src/images/component/lead-space/component--lead-space--variants.gif
  src/images/component/lead-space/lead-space-behavior-01.png
  src/images/component/lead-space/lead-space-behavior-02.png
  src/images/component/lead-space/lead-space-centered.png
  src/images/component/lead-space/lead-space-medium.png
  src/images/component/lead-space/lead-space-modifier-gradient-01.png
  src/images/component/lead-space/lead-space-modifier-gradient-02.png
  src/images/component/lead-space/lead-space-modifier-heading-highlight-01.png
  src/images/component/lead-space/lead-space-modifier-heading-highlight-02.png
  src/images/component/lead-space/lead-space-modifier-video.png
  src/images/component/lead-space/lead-space-modifier-wayfinding-01.png
  src/images/component/lead-space/lead-space-modifier-wayfinding-02.png
  src/images/component/lead-space/lead-space-overview.png
  src/images/component/lead-space/lead-space-short.png
  src/images/component/lead-space/lead-space-super.png
  src/images/component/lead-space/lead-space-tall.png
  src/pages/components/leadspace.mdx
Labels: hacktoberfest, v2
