Repository carbon-design-system/carbon-for-ibm-dotcom-website, pull requests merged in 2023-11, with the labels that each got.

#1711 Docs--remove tags v2
  src/data/components.json
  src/data/nav-items.yaml
  src/pages/components/tags.mdx
Labels: website, v2

#1706 Docs--images v2
  src/data/components.json
  src/images/component/image/image-modifier-border.png
  src/images/component/image/image-modifier-caption.png
  src/images/component/image/image-modifier-lightbox-01.png
  src/images/component/image/image-modifier-lightbox-02.png
  src/images/component/image/image-options-border.jpg
  src/images/component/image/image-options-caption.gif
  src/images/component/image/image-overview-default.jpg
  src/images/component/image/image-overview.png
  src/pages/components/images.mdx
Labels: hacktoberfest, v2

#1714 Docs dotcom shell updates
  src/data/components.json
  src/images/component/dotcom-shell/dotcom-shell-overview.png
  src/images/component/dotcom-shell/dotcomshell-overview.png
  src/pages/components/dotcom-shell.mdx
Labels: Ready to merge, v2

#1713 Docs--in-page-banner
  src/data/components.json
  src/data/nav-items.yaml
  src/pages/components/content-group-banner.mdx
  src/pages/components/in-page-banner.mdx
Labels: v2

#1712 feat(get-started): v2
  src/pages/developing/index.mdx
  src/pages/help/faqs.mdx
  src/pages/help/index.mdx
  src/pages/whats-happening/expressive-update.mdx
  src/pages/whats-happening/index.mdx
Labels: v2: prep, v2

#1705 Docs lead space block v2
  src/data/components.json
  src/images/component/lead-space-block/lead-space-block-modifier-heading-highlight-01.png
  src/images/component/lead-space-block/lead-space-block-modifier-heading-highlight-02.png
  src/images/component/lead-space-block/lead-space-block-overview.png
  src/images/pattern/lead-space-block/leadspace-block.jpg
  src/pages/components/lead-space-block.mdx
  src/pages/components/leadspace.mdx
Labels: hacktoberfest, v2

#1703 feat/docs--content-group
  src/data/components.json
  src/images/component/content-group/content-group-anatomy.png
  src/images/component/content-group/content-group-overview.png
  src/pages/components/content-group.mdx
Labels: hacktoberfest, v2

#1702 Docs -- tabs extended v2
  src/data/components.json
  src/images/component/tabs-extended/components--tabs-extended-1.png
  src/images/component/tabs-extended/components--tabs-extended-2.png
  src/images/component/tabs-extended/components--tabs-extended-3.png
  src/images/component/tabs-extended/components--tabs-extended-media-1.png
  src/images/component/tabs-extended/components--tabs-extended-media-2.png
  src/images/component/tabs-extended/tabs-extended-behavior-01.png
  src/images/component/tabs-extended/tabs-extended-behavior-02.png
  src/images/component/tabs-extended/tabs-extended-overview-01.png
  src/pages/components/tabs-extended.mdx
Labels: hacktoberfest, v2

#1700 Feat/docs table of contents
  src/images/component/table-of-contents/table-of-content-default-use-case.jpg
  src/images/component/table-of-contents/table-of-content-default.jpg
  src/images/component/table-of-contents/table-of-content-with-heading-content-use-case.jpg
  src/images/component/table-of-contents/table-of-content-with-heading-content.jpg
  src/images/component/table-of-contents/table-of-contents--default.png
  src/images/component/table-of-contents/table-of-contents--horizontal.png
  src/images/component/table-of-contents/table-of-contents--labels-horizontal.png
  src/images/component/table-of-contents/table-of-contents--labels-vertical.png
  src/images/component/table-of-contents/table-of-contents--small.png
  src/images/component/table-of-contents/table-of-contents--with-heading.png
  src/images/component/table-of-contents/table-of-contents-horizontal-use-case.jpg
  src/images/component/table-of-contents/table-of-contents-horizontal.jpg
  src/images/component/table-of-contents/table-of-contents-overview.png
  src/images/component/table-of-contents/table-of-contents.png
  src/images/component/table-of-contents/toc-horizontal-behavior-01.png
  src/images/component/table-of-contents/toc-horizontal-behavior-02.png
  src/images/component/table-of-contents/toc-horizontal-labels.png
  src/images/component/table-of-contents/toc-horizontal.png
  src/images/component/table-of-contents/toc-vertical-behavior-01.png
  src/images/component/table-of-contents/toc-vertical-behavior-02.png
  src/images/component/table-of-contents/toc-vertical-labels.png
  src/images/component/table-of-contents/toc-vertical.png
  src/pages/components/table-of-contents.mdx
Labels: hacktoberfest, v2

#1718 Docs--card - feature card - guidance update v2
  src/pages/components/cards.mdx
Labels: v2

#1723 feat(global-banner): v2 updates
  src/components/ComponentGallery/images/global_banner.svg
  src/data/components.json
  src/data/nav-items.yaml
  src/images/component/global-banner/global-banner--anatomy--060122.png
  src/images/component/global-banner/global-banner--behaviors--060122.png
  src/images/component/global-banner/global-banner--overview--060122.png
  src/images/component/global-banner/global-banner--with-image--060122.png
  src/images/component/global-banner/global-banner--with-text-only--060122.png
  src/pages/components/global-banner.mdx
  wiki/Layout-component/Global-banner.md
Labels: v2

#1720 Docs -- footer v2
  src/data/components.json
  src/data/nav-items.yaml
  src/images/component/footer/Footer_Demo_Default.jpg
  src/images/component/footer/Footer_Demo_Micro.png
  src/images/component/footer/Footer_Demo_Minimal.jpg
  src/images/component/footer/Footer_Demo_Minimal.png
  src/images/component/footer/Footer_Formatting_Footertypes.jpg
  src/images/component/footer/Footer_Intro.jpg
  src/images/component/footer/Footer_anatomy.jpg
  src/images/component/footer/footer--modifier-language.png
  src/images/component/footer/footer--modifier-locale.png
  src/images/component/footer/footer-anatomy.jpg
  src/images/component/footer/footer-behaviors.png
  src/images/component/footer/footer-demo-default.jpg
  src/images/component/footer/footer-demo-micro.jpg
  src/images/component/footer/footer-demo-minimal.jpg
  src/images/component/footer/footer-modifiers-01.png
  src/images/component/footer/footer-modifiers-02.png
  src/images/component/footer/footer-modifiers-03.png
  src/images/component/footer/footer-modifiers-04.png
  src/images/component/footer/footer-overview.png
  src/images/component/footer/footer-variants-01.png
  src/images/component/footer/footer-variants-02.png
  src/images/component/footer/footer-variants-03.png
  src/images/component/footer/footerV2-default-01.jpg
  src/images/component/footer/footerV2-default-anatomy.jpg
  src/images/component/footer/footerV2-default-behaviour.jpg
  src/images/component/footer/footerV2-default-withAdjunctlegallinks.jpg
  src/images/component/footer/footerV2-micro-01.jpg
  src/images/component/footer/footerV2-micro-anatomy.jpg
  src/images/component/footer/footerV2-micro-behaviour.jpg
  src/images/component/footer/footerV2-short-01.jpg
  src/images/component/footer/footerV2-short-anatomy.jpg
  src/images/component/footer/footerV2-short-behaviour.jpg
  src/images/component/footer/footerV2-short-withAdjunctlegallinks.jpg
  src/images/component/footer/footer_default_01.jpg
  src/images/component/footer/footer_default_02.jpg
  src/images/component/footer/footer_default_03.jpg
  src/images/component/footer/footer_default_anatomy.jpg
  src/images/component/footer/footer_default_behaviour.jpg
  src/images/component/footer/footer_default_withAdjunctlegallinks_02.jpg
  src/images/component/footer/footer_default_withAdjunctlegallinks_03.jpg
  src/images/component/footer/footer_micro_01.jpg
  src/images/component/footer/footer_micro_anatomy.jpg
  src/images/component/footer/footer_micro_behaviour.jpg
  src/images/component/footer/footer_short_01.jpg
  src/images/component/footer/footer_short_02.jpg
  src/images/component/footer/footer_short_03.jpg
  src/images/component/footer/footer_short_anatomy.jpg
  src/images/component/footer/footer_short_behaviour.jpg
  src/images/component/language-selector/language-selector-default.jpg
  src/images/component/language-selector/language-selector-use-case-01.jpg
  src/images/component/language-selector/language-selector-use-case-02.jpg
  src/images/component/language-selector/language-selector-use-case-03.jpg
  src/pages/components/footer.mdx
  src/pages/components/language-selector.mdx
Labels: v2

#1725 feat(carousel): update to v2
  src/data/components.json
  src/images/component/carousel/carousel-anatomy.png
  src/images/component/carousel/carousel-overview.png
  src/pages/components/carousel.mdx
Labels: Ready to merge, v2
